In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = [1,2,3,4,5,6,7,8]

In [ ]:
y=np.array([2,3,4,5])
y

array([2, 3, 4, 5])

In [ ]:
y.dtype

dtype('int64')

In [ ]:
y=np.array([2,3,4,5],float)

In [ ]:
y.dtype

dtype('float64')

In [ ]:
y.ndim

1

In [ ]:
y[2:5]

array([4., 5.])

In [ ]:
y

array([2., 3., 4., 5.])

In [ ]:
d =np.array([[1,2,3,4,5]])

In [ ]:
d.ndim

2

In [ ]:
d[0][4]

array([[1, 2, 3, 4, 5]])

In [ ]:
np.ones((3,6),int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [ ]:
np.full((4,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [ ]:
np.full((4,3),50)

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.arange(2,16,3)

array([ 2,  5,  8, 11, 14])

In [ ]:
np.linspace(2,8,20)

array([2.        , 2.31578947, 2.63157895, 2.94736842, 3.26315789,
       3.57894737, 3.89473684, 4.21052632, 4.52631579, 4.84210526,
       5.15789474, 5.47368421, 5.78947368, 6.10526316, 6.42105263,
       6.73684211, 7.05263158, 7.36842105, 7.68421053, 8.        ])

In [ ]:
np.random.randint(10)

1

In [ ]:
np.random.randint(1,10,6)

array([4, 7, 6, 6, 5, 2])

In [ ]:
np.random.randint(1,10,(2,2))

array([[6, 8],
       [9, 7]])

In [ ]:
arr=np.array([1,2,3,4,5])
arr=np.insert(arr,0,10)
arr

array([10,  1,  2,  3,  4,  5])

In [ ]:
np.delete(arr,4)

array([10,  1,  2,  3,  5])

In [ ]:
np.append(arr,7)

array([10,  1,  2,  3,  4,  5,  7])

In [ ]:
a=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
a.ndim

2

In [ ]:
np.insert(a,1,00,axis=1)

array([[ 1,  0,  2,  3,  4],
       [ 5,  0,  6,  7,  8],
       [ 9,  0, 10, 11, 12]])

In [ ]:
k=np.array([4,5,6,7])
k

array([4, 5, 6, 7])

In [ ]:
np.insert(a,2,k,axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 4,  5,  6,  7],
       [ 9, 10, 11, 12]])

In [ ]:
m=np.array([5,5,5,5])
m

array([5, 5, 5, 5])

In [ ]:
np.insert(a,3,m,axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 5,  5,  5,  5]])

In [ ]:
np.delete(a,3,axis=1)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [ ]:
a=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12],[2,3,4,5],[6,7,8,9]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(5, 4)

In [ ]:
a[1:4]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 2,  3,  4,  5]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [ ]:
a[2:4,1:3]

array([[10, 11],
       [ 3,  4]])